//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kidney
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string Method { get; set; }
        public int Degree1 { get; set; }
        public int Degree2 { get; set; }
        public int Degree3 { get; set; }
        public int Degree4 { get; set; }
        public int Degree5 { get; set; }
        public int Degree6 { get; set; }
        public string Cognition1 { get; set; }
        public string Cognition2 { get; set; }
        public string Cognition3 { get; set; }
        public string Cognition4 { get; set; }
        public string Cognition5 { get; set; }
        public string Cognition6 { get; set; }
        public string Cognition7 { get; set; }
        public string Cognition8 { get; set; }
        public string Cognition9 { get; set; }
        public string Cognition10 { get; set; }
        public string Yesno1 { get; set; }
        public string Yesno2 { get; set; }
        public string Yesno3 { get; set; }
        public string Decision { get; set; }
        public string Determine { get; set; }
        public string Text { get; set; }
        public int Token { get; set; }
        public string Ans1 { get; set; }
        public string Ans2 { get; set; }
        public string Ans3 { get; set; }
        public string Ans4 { get; set; }
        public string Ans5 { get; set; }
        public string Ans6 { get; set; }
        public string Ans7 { get; set; }
        public string Ans8 { get; set; }
        public string Ans9 { get; set; }
        public string Ans10 { get; set; }
        public string Ques1 { get; set; }
        public string Ques2 { get; set; }
        public string Ques3 { get; set; }
        public string Ques4 { get; set; }
        public string Ques5 { get; set; }
        public string Ques6 { get; set; }
        public string Ques7 { get; set; }
        public string Ques8 { get; set; }
        public string Ques9 { get; set; }
        public string Ques10 { get; set; }
        public string Result { get; set; }
        public int Dr_token { get; set; }
        public int Patient_token { get; set; }
        public int checkAnsTure { get; set; }
        public int checkAnsWrong { get; set; }
    }
}