//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace SDMProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string Name { get; set; }
        [Display(Name = "看診日期")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        public int Age { get; set; }
        public string DiseaseType { get; set; }
        public string Gender { get; set; }
        public string Form { get; set; }
        public string DrName { get; set; }
        public int CheckMsg { get; set; }
        public int CheckFinish { get; set; }
        public string Account { get; set; }

    }
}
